# Test data for AdminLTE Sentinel Framework

base.url=https://adminlte.io/themes/v3
datatable.page=/pages/tables/data.html
forms.page=/pages/forms/general.html
default.gender=male
default.status=active
